config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :links
  resources :views, path: :v, only: [:show]
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  # so if we destroy the link we delete the associate views
  has_many :views, dependent: :destroy

  #in order to reuse it
  scope :recent_first, -> { order(created_at: :desc)}

  validates :url, presence: true

  # to_param is a inbuild method of rails that give you the id here we are overwriting it
  def to_param
    ShortCode.encode(id)
  end

  # here also we are overwriting a inbuild metho of rails
  def self.find(id)
    super ShortCode.decode(id)
  end
  
  def domain
    URI(url).host rescue URI::InvalidURIError
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length

  def self.encode(number)
    return "0" if number.zero? || number.nil?

    result = ""

    while number > 0 do
      index = number % BASE
      char = ALPHABET[index]
      result.prepend char
      number = number / BASE
    end

    result
  end
  
  def self.decode(string)
    number = 0

    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET.index(char)
      number += index * power
    end

    number
  end
end

app/models/view.rb
class View < ApplicationRecord
  #any time we create a view we go an update the views_count on the links table
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    # @links = Link.order(created_at: :desc)
    # implement as a shorcut because it is common this is comming from the model using scope
    @links = Link.recent_first
    # if the @link is already defined lets skipped but its not then create a new necessary since we are coling index from else statement from create action
    @link ||= Link.new
  end

  def show
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_path
    else
      #we have to have the instance variable before render the index action because in the 
      #index view we are rendering @links and if we dont have we are going to get an error
      #@links = Link.recent_first
      #also we can call the index action:
      index
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path, notice: "Link has been deleted."
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link, only: [:show]

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: "Missing link!"
  end

  def show
    #its necessary if for example you want to detect boots
    @link.views.create(ip: request.ip, user_agent: request.user_agent)
    
    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favicon_helper.rb
module FaviconHelper
  def favicon_image_tag(domain, **kwargs)
    image_tag google_favicon_url(domain), **kwargs
  end
  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URLShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
        <%= tag.p alert, class: "bg-yellow-100 text-yellow-800 text-sm font-medium px-4 py-2 rounded" if alert %>
        <%= tag.p notice, class: "bg-green-100 text-green-800 text-sm font-medium px-4 py-2 rounded" if notice %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, required: true, autofocus: true, placeholder: "https://example.org", class: "flex-grow rounded"%>
    <%= form.button "Save", class: "px-3 py-2 bg-gray-100 rounded" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>

  <div class="grid grid-cols-8 items-center py-4">
    <div class="col-span-5">
      <%= link.url %>
      <%= link_to view_path(link), target: :_blank, data: {turbo: false}, class: "no-underline" do %>
        <%= favicon_image_tag link.domain, class: "inline-block" %>
        <%= link.url %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class=" inline-block w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>

    <div class="col-span-2 text-center text-xs">
      <%= link_to pluralize(link.views_count, "view"), link, class: "px-2 py-1.5 rounded bg-gray-100 no-underline" %>
    </div>

    <div class="text-center text-xs">
      <%= link_to "Copy", link, class: "px-2 py-1.5 rounded bg-gray-100 no-underline" %>
    </div>

  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render partial: "form", locals: {link: @link} %>

<div class="mt-4 flex gap-1 items-center">
  <%= link_to "Cancel", @link %>
  or
  <%= button_to "Delete", @link, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/links/index.html.erb
<h1>URL Shortener</h1>

<%= render partial: "form", locals: {link: @link} %>

<div class="mt-8 flex flex-col divide-y divide-gray-100">
  <%= render @links %>
</div>

app/views/links/show.html.erb
<div class=" flex justify-between items-center text-xs">
  <%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 rounded bg-gray-100" %>
  <div class="flex items-center gap-4">
    <%= tag.div pluralize(@link.views_count, "view")%>
    <%= link_to "Edit", edit_link_path(@link), class: "px-2 py-1.5 rounded bg-gray-100 no-underline" %>
  </div>
</div>

<h1 class="mt-4"><%= @link.url %></h1>
<%= @link.description %>

<%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "text-xs px-2 py-1.5 rounded bg-gray-100 no-underline" do %>
  <%= favicon_image_tag @link.domain, class: "inline-block" %>
  <%= @link.url %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class=" inline-block w-4 h-4">
    <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
  </svg>
<% end %>
<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>